media:
  input: public/assets/blog
  output: /assets/blog
  rename: safe
  categories: [image]

content:
  - name: posts-2026
    label: Blog posts
    type: collection
    path: src/content/blog/2026
    format: yaml-frontmatter
    filename:
      template: "{primary}.md"
      field: create
    subfolders: false
    operations:
      delete: false
    view:
      primary: title
      fields: [draft, pubDatetime, tags]
      sort: [pubDatetime, title]
      default:
        sort: pubDatetime
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: pubDatetime
        label: Publication date
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
      - name: description
        label: Description
        type: text
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: true
        required: true
      - name: unlisted
        label: Unlisted
        type: boolean
        default: false
      - name: featured
        label: Featured
        type: boolean
        default: false
      - name: tags
        label: Tags
        type: string
        list: true
        default: []
      - name: heroImage
        label: Hero image
        type: image
        required: false
      - name: heroImageAlt
        label: Hero image alt text
        type: string
        required: false
      - name: heroImageCaption
        label: Hero image caption
        type: string
        required: false
      - name: ogImage
        label: Social sharing image
        type: image
        required: false
      - name: author
        label: Author
        type: string
        default: Justin Carlson
        required: false
      - name: modDatetime
        label: Last modified
        type: date
        required: false
        default: ""
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssXXX
      - name: body
        label: Article
        type: rich-text
        required: true

settings:
  content:
    merge: true
  commit:
    identity: user
    templates:
      create: "content: create {filename}"
      update: "content: update {filename}"
      delete: "content: delete {filename}"
      rename: "content: rename {oldFilename} to {newFilename}"
